version: "3.1"

services:
  app:
    depends_on:
       - db
    image: artem06/code-masters:1.2
    ports:
      - "5202:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development  
      ConnectionStrings__DefaultConnection: 
        "Host=db;Port=5432;Database=Freelance;Username=postgres;Password=1111"
      Jwt__secret: secret060606gfghdgdsfgfdgergsdfdgrrer
      Jwt__Issuer: http://localhost:5202
      Jwt__Audience: http://localhost:5202
      Jwt__Lifetime: 43200
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: Freelance